env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 13
  sourceType: module
plugins:
  - react
rules: {
  "indent": ["error", 2],
  "react/prop-types": "off",
  "eol-last": ["error", "always"],
  "no-trailing-spaces": "error",
  "space-infix-ops": ["error", { "int32Hint": false }],
  "semi": [2, "always"]
}

settings:
  react:
    version: 17.0.2
