env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 13
  sourceType: module
plugins:
  - react
<<<<<<< HEAD
rules: {
  "indent": ["error", 2],
  "react/prop-types": "off"
}
=======
rules: {}
>>>>>>> 16f7fbd (CI/CD: Added eslint and github workflow for ci)
