name: ci
on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint
        run: |
          npm install
          npm run lint
      - name: Run CI
        run: npm ci
      - name: Build
        run: npm run build
